[package]
name = "nimbuslink_server"
version = "0.1.0"
edition = "2021"


[workspace]
members = ["libs/nimbus_common"]

[dependencies]
nimbus_common = { path = "libs/nimbus_common" }
# get local ip address
local-ip-address = "0.5.6"
# web socket
tungstenite = "0.20.1"
tokio-tungstenite = "0.20.1"