[package]
name = "nimbuslink_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["libs/nimbus_common"]

[dependencies]
nimbus_common = {path = "libs/nimbus_common"}