// This file is generated by rust-protobuf 3.3.0. Do not edit
// .proto file is parsed by pure
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `rendezvous.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_3_0;

// @@protoc_insertion_point(message:nimbus.RegisterPeer)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RegisterPeer {
    // message fields
    // @@protoc_insertion_point(field:nimbus.RegisterPeer.id)
    pub id: ::std::string::String,
    // @@protoc_insertion_point(field:nimbus.RegisterPeer.serial)
    pub serial: i32,
    // special fields
    // @@protoc_insertion_point(special_field:nimbus.RegisterPeer.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RegisterPeer {
    fn default() -> &'a RegisterPeer {
        <RegisterPeer as ::protobuf::Message>::default_instance()
    }
}

impl RegisterPeer {
    pub fn new() -> RegisterPeer {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "id",
            |m: &RegisterPeer| { &m.id },
            |m: &mut RegisterPeer| { &mut m.id },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "serial",
            |m: &RegisterPeer| { &m.serial },
            |m: &mut RegisterPeer| { &mut m.serial },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RegisterPeer>(
            "RegisterPeer",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RegisterPeer {
    const NAME: &'static str = "RegisterPeer";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.id = is.read_string()?;
                },
                16 => {
                    self.serial = is.read_int32()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.id.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.id);
        }
        if self.serial != 0 {
            my_size += ::protobuf::rt::int32_size(2, self.serial);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.id.is_empty() {
            os.write_string(1, &self.id)?;
        }
        if self.serial != 0 {
            os.write_int32(2, self.serial)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RegisterPeer {
        RegisterPeer::new()
    }

    fn clear(&mut self) {
        self.id.clear();
        self.serial = 0;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RegisterPeer {
        static instance: RegisterPeer = RegisterPeer {
            id: ::std::string::String::new(),
            serial: 0,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RegisterPeer {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RegisterPeer").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RegisterPeer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RegisterPeer {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:nimbus.RegisterPeerResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RegisterPeerResponse {
    // message fields
    // @@protoc_insertion_point(field:nimbus.RegisterPeerResponse.request_pk)
    pub request_pk: bool,
    // special fields
    // @@protoc_insertion_point(special_field:nimbus.RegisterPeerResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RegisterPeerResponse {
    fn default() -> &'a RegisterPeerResponse {
        <RegisterPeerResponse as ::protobuf::Message>::default_instance()
    }
}

impl RegisterPeerResponse {
    pub fn new() -> RegisterPeerResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "request_pk",
            |m: &RegisterPeerResponse| { &m.request_pk },
            |m: &mut RegisterPeerResponse| { &mut m.request_pk },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RegisterPeerResponse>(
            "RegisterPeerResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RegisterPeerResponse {
    const NAME: &'static str = "RegisterPeerResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                16 => {
                    self.request_pk = is.read_bool()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if self.request_pk != false {
            my_size += 1 + 1;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if self.request_pk != false {
            os.write_bool(2, self.request_pk)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RegisterPeerResponse {
        RegisterPeerResponse::new()
    }

    fn clear(&mut self) {
        self.request_pk = false;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RegisterPeerResponse {
        static instance: RegisterPeerResponse = RegisterPeerResponse {
            request_pk: false,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RegisterPeerResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RegisterPeerResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RegisterPeerResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RegisterPeerResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

// @@protoc_insertion_point(message:nimbus.RendezvousMessage)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct RendezvousMessage {
    // message oneof groups
    pub union: ::std::option::Option<rendezvous_message::Union>,
    // special fields
    // @@protoc_insertion_point(special_field:nimbus.RendezvousMessage.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a RendezvousMessage {
    fn default() -> &'a RendezvousMessage {
        <RendezvousMessage as ::protobuf::Message>::default_instance()
    }
}

impl RendezvousMessage {
    pub fn new() -> RendezvousMessage {
        ::std::default::Default::default()
    }

    // .nimbus.RegisterPeer register_peer = 6;

    pub fn register_peer(&self) -> &RegisterPeer {
        match self.union {
            ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(ref v)) => v,
            _ => <RegisterPeer as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_register_peer(&mut self) {
        self.union = ::std::option::Option::None;
    }

    pub fn has_register_peer(&self) -> bool {
        match self.union {
            ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_register_peer(&mut self, v: RegisterPeer) {
        self.union = ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(v))
    }

    // Mutable pointer to the field.
    pub fn mut_register_peer(&mut self) -> &mut RegisterPeer {
        if let ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(_)) = self.union {
        } else {
            self.union = ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(RegisterPeer::new()));
        }
        match self.union {
            ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_register_peer(&mut self) -> RegisterPeer {
        if self.has_register_peer() {
            match self.union.take() {
                ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(v)) => v,
                _ => panic!(),
            }
        } else {
            RegisterPeer::new()
        }
    }

    // .nimbus.RegisterPeerResponse register_peer_response = 7;

    pub fn register_peer_response(&self) -> &RegisterPeerResponse {
        match self.union {
            ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(ref v)) => v,
            _ => <RegisterPeerResponse as ::protobuf::Message>::default_instance(),
        }
    }

    pub fn clear_register_peer_response(&mut self) {
        self.union = ::std::option::Option::None;
    }

    pub fn has_register_peer_response(&self) -> bool {
        match self.union {
            ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_register_peer_response(&mut self, v: RegisterPeerResponse) {
        self.union = ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(v))
    }

    // Mutable pointer to the field.
    pub fn mut_register_peer_response(&mut self) -> &mut RegisterPeerResponse {
        if let ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(_)) = self.union {
        } else {
            self.union = ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(RegisterPeerResponse::new()));
        }
        match self.union {
            ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_register_peer_response(&mut self) -> RegisterPeerResponse {
        if self.has_register_peer_response() {
            match self.union.take() {
                ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(v)) => v,
                _ => panic!(),
            }
        } else {
            RegisterPeerResponse::new()
        }
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(1);
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, RegisterPeer>(
            "register_peer",
            RendezvousMessage::has_register_peer,
            RendezvousMessage::register_peer,
            RendezvousMessage::mut_register_peer,
            RendezvousMessage::set_register_peer,
        ));
        fields.push(::protobuf::reflect::rt::v2::make_oneof_message_has_get_mut_set_accessor::<_, RegisterPeerResponse>(
            "register_peer_response",
            RendezvousMessage::has_register_peer_response,
            RendezvousMessage::register_peer_response,
            RendezvousMessage::mut_register_peer_response,
            RendezvousMessage::set_register_peer_response,
        ));
        oneofs.push(rendezvous_message::Union::generated_oneof_descriptor_data());
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<RendezvousMessage>(
            "RendezvousMessage",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for RendezvousMessage {
    const NAME: &'static str = "RendezvousMessage";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                50 => {
                    self.union = ::std::option::Option::Some(rendezvous_message::Union::RegisterPeer(is.read_message()?));
                },
                58 => {
                    self.union = ::std::option::Option::Some(rendezvous_message::Union::RegisterPeerResponse(is.read_message()?));
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.union {
            match v {
                &rendezvous_message::Union::RegisterPeer(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
                &rendezvous_message::Union::RegisterPeerResponse(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if let ::std::option::Option::Some(ref v) = self.union {
            match v {
                &rendezvous_message::Union::RegisterPeer(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(6, v, os)?;
                },
                &rendezvous_message::Union::RegisterPeerResponse(ref v) => {
                    ::protobuf::rt::write_message_field_with_cached_size(7, v, os)?;
                },
            };
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> RendezvousMessage {
        RendezvousMessage::new()
    }

    fn clear(&mut self) {
        self.union = ::std::option::Option::None;
        self.union = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static RendezvousMessage {
        static instance: RendezvousMessage = RendezvousMessage {
            union: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for RendezvousMessage {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("RendezvousMessage").unwrap()).clone()
    }
}

impl ::std::fmt::Display for RendezvousMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for RendezvousMessage {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `RendezvousMessage`
pub mod rendezvous_message {

    #[derive(Clone,PartialEq,Debug)]
    #[non_exhaustive]
    // @@protoc_insertion_point(oneof:nimbus.RendezvousMessage.union)
    pub enum Union {
        // @@protoc_insertion_point(oneof_field:nimbus.RendezvousMessage.register_peer)
        RegisterPeer(super::RegisterPeer),
        // @@protoc_insertion_point(oneof_field:nimbus.RendezvousMessage.register_peer_response)
        RegisterPeerResponse(super::RegisterPeerResponse),
    }

    impl ::protobuf::Oneof for Union {
    }

    impl ::protobuf::OneofFull for Union {
        fn descriptor() -> ::protobuf::reflect::OneofDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::OneofDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| <super::RendezvousMessage as ::protobuf::MessageFull>::descriptor().oneof_by_name("union").unwrap()).clone()
        }
    }

    impl Union {
        pub(in super) fn generated_oneof_descriptor_data() -> ::protobuf::reflect::GeneratedOneofDescriptorData {
            ::protobuf::reflect::GeneratedOneofDescriptorData::new::<Union>("union")
        }
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x10rendezvous.proto\x12\x06nimbus\"6\n\x0cRegisterPeer\x12\x0e\n\x02i\
    d\x18\x01\x20\x01(\tR\x02id\x12\x16\n\x06serial\x18\x02\x20\x01(\x05R\
    \x06serial\"5\n\x14RegisterPeerResponse\x12\x1d\n\nrequest_pk\x18\x02\
    \x20\x01(\x08R\trequestPk\"\xaf\x01\n\x11RendezvousMessage\x12;\n\rregis\
    ter_peer\x18\x06\x20\x01(\x0b2\x14.nimbus.RegisterPeerH\0R\x0cregisterPe\
    er\x12T\n\x16register_peer_response\x18\x07\x20\x01(\x0b2\x1c.nimbus.Reg\
    isterPeerResponseH\0R\x14registerPeerResponseB\x07\n\x05unionb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(3);
            messages.push(RegisterPeer::generated_message_descriptor_data());
            messages.push(RegisterPeerResponse::generated_message_descriptor_data());
            messages.push(RendezvousMessage::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
